import { ToastProvider } from '@/lib/provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '바이블 25 | 어드민',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
  icons: [
    {
      rel: 'icon',
      url: './favicon.ico',
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <meta charSet="utf-8" />
        <meta property="og:image" content={'/oglogo.jpeg'} />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:title" content="바이블 25" />
        <meta property="og:description" content="바이블 25 관리자 페이지입니다." />
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </head>
      <body>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
